config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  root to: "books#top"
  delete "books/:id" => "books#destroy", as: "destroy_book"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  	@books = Book.all
  end

  def show
  	@book = Book.find(params[:id])
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
  		flash[:notice] = "Book was successfully created."
  		redirect_to book_path(@book.id)
  	else
  		@books = Book.all
  		render action: :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		flash[:notice] = "Book was successfully created."
  		redirect_to book_path(@book)
  	else
  		render action: :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!--Alert-->
<% if @book.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
	<div>
		<h5>Title</h5>
		<%= f.text_field :title %>
	</div>
	<div>
		<h5>Body</h5>
		<%= f.text_area :body %>
	</div>
	<div><%= f.submit "Update Book" %></div>
	<h4>
		<%= link_to "Show", book_path(@book.id) %>
		|
		<%= link_to "Back", books_path %>
	</h4>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
	<table>
		<thead>
			<tr valign = "top">
				<th width = "100" height = "20">Title</th>
				<th width = "400" height = "20">Body</th>
				<th colspan = "3"></th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
				<tr>
					<td><%= book.title %></td>
					<td><%= book.body %></td>
					<td width = "20"><%= link_to "Show", book_path(book.id) %></td>
					<td width = "20"><%= link_to "Edit", edit_book_path(book.id) %></td>
					<td width = "20"><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか?" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

<h1>New Book</h1>

<%= form_for(@book, url: "/books")  do |f| %>

<!--Alert-->
<% if @book.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div>
	<h4>Title</h4>
	<%= f.text_field :title %>
</div>
<div>
	<h4>Body</h4>
	<%= f.text_area :body %>
</div>
<div><%= f.submit "Create Book" %></div>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<div class = "flash">
		<%= flash[:notice] %>
	</div>
<% end %>

<div  class = "show-text_body">
	<strong>Title:</strong>
	<%= @book.title %>
</div>
<div  class = "show-text_body">
	<strong>Body:</strong>
	<%= @book.body %>
</div>
<h4>
	<a class = "show-icon">
		<%= link_to "Edit", edit_book_path(@book.id) %>
	</a>
	|
	<a class = "show-icon">
		<%= link_to "Back", books_path %>
	</a>
</h4>

app/views/books/top.html.erb
<div class = "top-title">
	<h2>ようこそ Bookersへ！</h2>
</div>
<div class = "top-body">
	<h5>Bookersでは、さまざまな書籍に関するあなたの意見や</h5>
	<h5>印象を共有し交換することができます</h5>
	<h4><%= link_to "Start", books_path %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= yield %>
  <body>
  </body>
</html>